modLoader="javafml"
loaderVersion="${forge_loader_range}"
issueTrackerURL="https://github.com/bernie-g/geckolib/issues"
license="${mod_license}"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_display_name}"
    displayURL="http://geckolib.com/"
    logoFile="geckolib.png"
    authors="${mod_authors}"
    credits="${mod_contributors}"
    description='''
${mod_description}
'''

[[dependencies.geckolib]]
    modId="forge"
    mandatory=true 
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.geckolib]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"