[versions]
# GeckoLib
    geckolib = "5.3"

# Common
    minecraft-range = "[1.21.8,)"
    minecraft = "1.21.8"
    parchment-minecraft = "1.21.8"
    parchment = "2025.09.14"
    neoform = "1.21.8-20250717.133445"
    jopt-simple = "5.0.4"

# Fabric
    fabric = "0.17.2"
    fabric-range = "0.17"
    fabric-api = "0.133.4+1.21.8"
    fabric-api-range = "0.130.0+1.21.8"

# Forge
    forge-fml-range = "[58,)"
    forge-range = "[58.1.0,)"
    forge = "58.1.2"
    forge-mc = "1.21.8-58.1.2"

# Neoforge
    neoforge-loader-range = "[5,)"
    neoforge-range = "[21.8.30,)"
    neoforge = "21.8.47"

# Dependencies
    mixin = "0.8.7"
    mixinextras = "0.5.0"
    mixinextras-range = "[0.5.0,)"
    examplemod = "1.0.0"
    iris = "kuOV4Ece"

# Plugins
    plugin-moddevgradle = "2.0.107"
    plugin-minotaur = "2.8.7"
    plugin-curseforge-gradle = "1.1.26"
    plugin-idea-ext = "1.1.10"
    plugin-forge-gradle = "[6.0.44,6.2)"
    plugin-mixin = "0.7.+"
    plugin-parchment-forge-gradle = "1.+"
    plugin-loom = "1.10-SNAPSHOT"

[libraries]
# Mixin
    mixin = { group = "org.spongepowered", name = "mixin", version.ref = "mixin" }
    mixinextras-common = { group = "io.github.llamalad7", name = "mixinextras-common", version.ref = "mixinextras" }
    mixinextras-forge = { group = "io.github.llamalad7", name = "mixinextras-forge", version.ref = "mixinextras" }

# Platform
    neoforge = { group = "net.neoforged", name = "neoforge", version.ref = "neoforge" }
    forge = { group = "net.minecraftforge", name = "forge", version.ref = "forge-mc" }
    fabric = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric" }
    fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
    minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }

# Testing
    examplemod-common = { group = "software.bernie.geckolib", name = "geckolib-examples-ml-common-1.21.8", version.ref = "examplemod" }
    examplemod-fabric = { group = "software.bernie.geckolib", name = "geckolib-examples-ml-fabric-1.21.8", version.ref = "examplemod" }
    examplemod-forge = { group = "software.bernie.geckolib", name = "geckolib-examples-ml-forge-1.21.8", version.ref = "examplemod" }
    examplemod-neoforge = { group = "software.bernie.geckolib", name = "geckolib-examples-ml-neoforge-1.21.8", version.ref = "examplemod" }

# Other
    jopt-simple = { group = "net.sf.jopt-simple", name = "jopt-simple", version.ref = "jopt-simple" } # Forge's temporary hacky solution
    iris = { group = "maven.modrinth", name = "iris", version.ref = "iris" }

[plugins]
# Publishing
    minotaur = { id = "com.modrinth.minotaur", version.ref = "plugin-minotaur" }
    curseforgegradle = { id = "net.darkhax.curseforgegradle", version.ref = "plugin-curseforge-gradle" }

# Platform
    moddevgradle = { id = "net.neoforged.moddev", version.ref = "plugin-moddevgradle" }
    forgegradle = { id = "net.minecraftforge.gradle", version.ref = "plugin-forge-gradle" }
    loom = { id = "fabric-loom", version.ref = "plugin-loom" }
    parchmentforgegradle = { id = "org.parchmentmc.librarian.forgegradle", version.ref = "plugin-parchment-forge-gradle" }

# Misc
    ideaext = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "plugin-idea-ext" }
    mixin = { id = "org.spongepowered.mixin", version.ref = "plugin-mixin" }