modLoader="javafml"
loaderVersion="${neoforge_loader_range}"
issueTrackerURL="https://github.com/bernie-g/geckolib/issues"
license="${mod_license}"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_display_name}"
    displayURL="http://geckolib.com/"
    logoFile="geckolib.png"
    authors="${mod_authors}"
    credits="${mod_contributors}"
    description='''
${mod_description}
'''

[[mixins]]
    config = "${mod_id}.mixins.json"

[[accessTransformers]]
    file = "META-INF/accesstransformer-nf.cfg"

[[dependencies.geckolib]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.geckolib]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"